### ISSUE TITLE
Gets error when open sample project

### ISSUE THREAD

**Issue by Horray** [PhamBaTho/BTNavigationDropdownMenu#11]
I opened up the sample project, and I had 9 errors and 1 warning. If you can fix them that would be greatly appreciated!

**Comment by PhamBaTho** [comment]
@Horray what XCode version are you using? I guess it's XCode 6.4, right?

**Comment by MattFedo** [comment]
Same issues.  Xcode 6.4 / Swift 1.2

**Comment by Horray** [comment]
Yes. Do I need a newer version for this?

**Comment by dimohamdy** [comment]
same Issue

**Comment by mt-hodaka** [comment]
same issue.  
Xcode 6.4, swift 1.2

**Comment by PhamBaTho** [comment]
Use branch [swift-1.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/tree/swift-1.2) for XCode 6.4, Swift 1.2. In Podfile, you have to change to branch 1.2 as instruction in README:
```swift
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-1.2'
```
I think tomorrow Apple will release official XCode 7, fully support Swift 2.0. Sooner or later, your apps should be support iOS 9 Swift 2.0, therefore, I decided to keep Swift 2.0 in master branch.
