### ISSUE TITLE
to use the menu to instantiate other view controllers

### ISSUE THREAD

**Issue by Mwiti** [PhamBaTho/BTNavigationDropdownMenu#12]
As it is, the control is using only one viewController. How would I use the control so that when i select a row in it, I instantiate another view controller. I'm doing it this way: 

            ...
            print("Did select item at index: \(indexPath)")
            let vc = self.storyboard?.instantiateViewControllerWithIdentifier(self.items[indexPath])
            
            self.presentViewController(vc!, animated: true, completion: nil)
        }

and it does work. it brings up a vc with the identifier as is labelled in the storyboard except i lose the navigation bar along with the menu when i select any other viewController except the one that's embedded in a navigationController. 

I've tried embedding all the VC's in their own navigationControllers but nothing.
I've tried copying all the 'menuView' code into each of the viewController's classes but I still don't get the menu when I select a different viewController. 

Assist me please? *sorry if its kind of a noob question. I'm only just learning Swift. Thanks!

**Comment by PhamBaTho** [comment]
@Mwiti: I don't understand what exactly you're trying to do with bringing up controllers. But you can try to present navigation controller instead of individually view controller:
```
let navigationController = UINavigationController(rootViewController: vc)
self.presentViewController(navigationController, animated: true, completion: nil)
```
