### ISSUE TITLE
Error compiling project after install via CocoaPods

### ISSUE THREAD

**Issue by ebenj** [PhamBaTho/BTNavigationDropdownMenu#127]
Hi,

I have just installed BTNavigationDropdownMenu via CocoaPods. Now when I compile my project I get 83 errors related to BTNavigationDropdownMenu pod.

Is there anything I should change?

Demo project worked fine.

**Comment by sacred0x01** [comment]
Add pod in that way
pod 'BTNavigationDropdownMenu', :git => 
'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git'

It should works fine.

**Comment by ebenj** [comment]
Thanks. It worked

**Comment by cdunkel** [comment]
@sacred0x01 do you know why that change is necessary or what the difference is between specifying the git repo and just adding the lib through Cocoapods?

**Comment by sacred0x01** [comment]
@cdunkel it's because of some errors in podfile. May be wrong branch on something like that. Or podspec just outdated. Anyway right now author left this project)

**Comment by PhamBaTho** [comment]
@sacred0x01 I suspect that `pod repo update` was not run for a while, which might lead to the conflict between `podspec` in CocoaPods Master Repo and `podspec` in this repo. 

Relating to above 83 errors, it could be the misuse of v.0.4.1 as I mentioned here https://github.com/PhamBaTho/BTNavigationDropdownMenu/issues/144#issuecomment-424429749.

I'm not abandoning this project, I had some personal issues last year so I couldn't maintain the project at that time. Now I'm back. Feel free to let me know if any improvement needed. Thanks.

**Comment by cdunkel** [comment]
@PhamBaTho, not sure if this is related at all to the issues that @sacred0x01 was seeing, but I did notice that when using the `swift-3.0` branch of this project the project is still set to use Swift 4. That is why my Podfile needed that post-install script to reset the Swift version back to 3.

If I have time later I can see about creating a PR with a fix for that, if that really is an issue.
