### ISSUE TITLE
Xcode 9 support

### ISSUE THREAD

**Issue by alexvazquez** [PhamBaTho/BTNavigationDropdownMenu#132]
Im getting errors when compiling with Xcode 9 and Swift 3.2.

**Comment by nidhig-sminq** [comment]
I am getting same issue, lot of errors with xcode 9. Any solution on this ?

**Comment by zkrige** [comment]
#135 fixes this

**Comment by PhamBaTho** [comment]
I have just added [support for Xcode 10 and Swift 4.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.5).
