### ISSUE TITLE
REPO UNMAINTAINED (FORKED)

### ISSUE THREAD

**Issue by hammadzz** [PhamBaTho/BTNavigationDropdownMenu#142]
Please open issues up in Fork.  I will start maintaining it there as the author has disappeared.
https://github.com/hammadzz/NavBarDropdownMenu

**Comment by PhamBaTho** [comment]
I will be back next week with Swift 4.2 supported. Stay tuned.

**Comment by PhamBaTho** [comment]
I have just added [support for Xcode 10 and Swift 4.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.5).

**Comment by hammadzz** [comment]
@PhamBaTho awesome thanks!
