### ISSUE TITLE
Errors when using CocoaPods install as directed

### ISSUE THREAD

**Issue by cdunkel** [PhamBaTho/BTNavigationDropdownMenu#144]
This is similar to the issue reported [here].(https://github.com/PhamBaTho/BTNavigationDropdownMenu/issues/127)

Our application, which is a mix of both Swift and Obj C code, has been using this library for quite a while. Our Podfile was using the following format:

`pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git'`

With the release of Swift 4.2 this library was updated and we started seeing errors. We're trying to specify a specific version of this library to use, specifically 0.4.1, with the podfile format:

`pod 'BTNavigationDropdownMenu', '= 0.4.1'`

However, that is giving us the 87 errors referenced in the issue linked at the top of this post. Even when following the guide in the [Installation instructions](https://github.com/PhamBaTho/BTNavigationDropdownMenu#installation) we're seeing errors.

My questions are:

1. Does anyone know the cause of these errors?
2. What is the difference between specifying the pod using the standard `pod 'BTNavigationDropdownMenu'` format and having it point directly to the repo with the `:git =>` flag?

**Comment by cdunkel** [comment]
I just checked and we're using Swift 4.0. I'll try pointing directly to the `swift-4.0` branch and see if that works.

I haven't had a chance to review the Swift 4.2 changes. Do you think there would be significant impact in updating our Swift version?

**Comment by PhamBaTho** [comment]
Yes, please help me test it. That branch was merged from contributors and I haven't had time to test it yet. Please feel free to open PR if any. Thanks.

I'm not sure how big your project is and how many dependencies you're using in your application, but I have recently updated to 4.2 in my 3 projects, I personally feel the effort of upgrading from 4.0 to 4.2 is quite far less hassle than from 3.x to 4.0.

**Comment by cdunkel** [comment]
Using the `swift-4.0` branch I'm still getting the following issues:
![image](https://user-images.githubusercontent.com/685932/46032072-a0e2a400-c0c8-11e8-9d21-a38886bb167a.png)

I'll try updating the project to Swift 4.2 and see if that changes anything.

**Comment by PhamBaTho** [comment]
Hmmm, I don't have 4.0 here to test, but you can check the PR https://github.com/PhamBaTho/BTNavigationDropdownMenu/pull/138 and https://github.com/PhamBaTho/BTNavigationDropdownMenu/pull/135 and https://github.com/PhamBaTho/BTNavigationDropdownMenu/pull/133. All of the PRs were having the same purpose of updating to Swift 4.0. And seems the changes in these PRs are relating exactly the errors you got. So please help me check your version Xcode again. I suspects you're using Swift 3.2.

You can also check the link: https://stackoverflow.com/questions/46520306/type-nsattributedstringkey-aka-nsstring-has-no-member-font, they all have the same issues and the fix is to change the Swift language version here:
![image](https://user-images.githubusercontent.com/5548600/46032765-11241080-c12f-11e8-923a-dca892d0f094.png)

**Comment by cdunkel** [comment]
I'm running the latest Xcode 10.0. I did verify that my project target is set to Swift 4, just as indicated in the screenshot and link you shared.

I ended up figuring out that my Podfile had an old post-install section that was setting the Swift version of most of the pod targets to 3.0. After removing that and using the pod entry that targets the `swift-4.0` branch I was able to successfully build the library.

Now I'm getting some complaints when building my project target:
![image](https://user-images.githubusercontent.com/685932/46034889-bf986900-c0cf-11e8-9a06-9bb72440bf33.png)

Are these errors consistent with any API updates that were made to the lib?

**Comment by cdunkel** [comment]
I should also mention that I'm making calls against BTNavigationDropdownMenu from an Objective C class, so if any changes were made impacting the visibility of methods in Objective C that would be an issue for me.

**Comment by cdunkel** [comment]
Updating my project to Swift 4.2 and using `pod 'BTNavigationDropdownMenu'` to grab version 0.5 also succeeds in building the library, but I get the same project errors as above.

**Comment by cdunkel** [comment]
Thanks, I didn't realize there was an Objective C fork of this. It's becoming more and more difficult to find 3rd party libraries that will work with a legacy Objective C app, haha.

Thank you also for your quick responses on this issue.

Do you happen to know if anything was done in the recent update that would impact Objective C support? I looked at the most recent merge, but nothing was obvious to me. Thanks!

**Comment by PhamBaTho** [comment]
I have the same thought until you raised the issue with Objective C. I will def have a look at this when I have free time, but I don't think it's in high priority because I don't think Objective C is popular at this moment.

**Comment by cdunkel** [comment]
I'll also take a look when I get some time and see if there's anything that I can submit as a PR.

Objective C actually [still has strong support](https://www.tiobe.com/tiobe-index/), but I know Swift is still the new favorite thing and that's where developers want to focus their efforts. It's too bad that Objective C doesn't get more love anymore, especially since there are millions of existing apps that were written before Swift that are still being updated regularly and would like to be able to use the latest and greatest libraries.
