### ISSUE TITLE
carthage framework scheme error

### ISSUE THREAD

**Issue by Bang9** [PhamBaTho/BTNavigationDropdownMenu#148]
Dependency "BTNavigationDropdownMenu" has no shared framework schemes

![image](https://user-images.githubusercontent.com/26326015/50504133-d8d5fa80-0aae-11e9-9e7d-cdded029de77.png)

**Comment by Bang9** [comment]
![image](https://user-images.githubusercontent.com/26326015/50504293-f0fa4980-0aaf-11e9-8c1b-73755f896bfb.png)

all of tag versions are not include xcode project...
so carthage can not recognized framework schemes

**Comment by Tobisaninfo** [comment]
I've got the same error. How can I fix this problem ?

**Comment by Bang9** [comment]
> I've got the same error. How can I fix this problem ?
for you :)
```
github "PhamBaTho/BTNavigationDropdownMenu" "master"
```

**Comment by PhamBaTho** [comment]
hey @Bang9 @Tobisaninfo I added tag `0.6` with Carthage support. It should work properly now.
