### ISSUE TITLE
Hide dropDownMenu when tapping outside its bounds

### ISSUE THREAD

**Issue by olbartek** [PhamBaTho/BTNavigationDropdownMenu#16]
Hello, is it possible to hide menu when a user taps outside its bounds? If not, could you give me a hint to which view should I add a tapGestureRecognizer?

Thanks in advance

**Comment by justindhill** [comment]
Hi, I needed this as well, so I implemented it in PR #22. If you still need it, you can find it in https://github.com/justindhill/BTNavigationDropdownMenu/tree/tap-background-to-dismiss

**Comment by TheBogueRat** [comment]
Thanks, this should be pulled into the main branch.  Now I'm only missing a way to dismiss the menu on back navigation... The other issue's solution did not work for me.

**Comment by justindhill** [comment]
Glad it helped you!

**Comment by SjoerdPerfors** [comment]
Thanks, needed this as wel :+1:

**Comment by PhamBaTho** [comment]
@olbartek @TheBogueRat @SjoerdPerfors: Merged PR of @justindhill in [release 0.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.2). Thanks!
