### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by bfrolicher** [PhamBaTho/BTNavigationDropdownMenu#162]
Hi,

I would like to know if this project is still being maintained?
There are 13 PRs and 50 issues.
The swift 5 support is still not present, the last release was almost 2 years ago.
I can make a pull request to add it and fix all warnings, but I have to know if I should do in a fork or in this repo.

Thank you for your answer.

Sincerely

**Comment by PhamBaTho** [comment]
@bfrolicher thanks for reaching out. Yes it's still being maintained, I will focus more on this repo to keep it updated. Please help submit your PR to support Swift 5 if you have time. Cheers.

**Comment by PhamBaTho** [comment]
update: I have just released [v0.7](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.7) which supports Swift 5 and fixes all warnings.
