### ISSUE TITLE
Keep navigation title static

### ISSUE THREAD

**Issue by mirzadelic** [PhamBaTho/BTNavigationDropdownMenu#18]
Hi,
can i keep navigation title static.
I need to keep it, even when i choose some item from dropdown.

**Comment by TheBogueRat** [comment]
search the BTNavigationDropdownMenu for "= title" and replace 'title' in both spots with the static text you want, in quotes.

**Comment by mirzadelic** [comment]
That's not solution, need to set different for many controllers..

**Comment by TheBogueRat** [comment]
That's a good point!  It worked great for my single instance but I didn't think it through for your scenario.  These are two very different approaches so I suppose you'd have to send a flag with the init that could be used to determine if you sent a string literal or a string from the array.  However, I started down this road so try this.  Comment out where the title is assigned in the BTNavigationDropdownMenu.swift file:

        self.tableView.selectRowAtIndexPathHandler = { (indexPath: Int) -> () in
            self.didSelectItemAtIndexHandler!(indexPath: indexPath)
//          self.setMenuTitle("\(items[indexPath])")
            self.hideMenu()
            self.layoutSubviews()
        }

And in your .swift initialize it with your title: (Draw Menu in my case)

        let menuView = BTNavigationDropdownMenu(title: "Draw Menu", items: items)

**Comment by RishabhTayal** [comment]
Implemented this and created a PR: https://github.com/PhamBaTho/BTNavigationDropdownMenu/pull/75

**Comment by PhamBaTho** [comment]
@mirzadelic @TheBogueRat: PR #75 @RishabhTayal mentioned above has just been merged. Thanks RishabhTayal again for helping implement this feature.
Please feel free to reopen if you guys have any other concerns.
