### ISSUE TITLE
let menuView = BTNavigationDropdownMenu(title: items.first!, items: items) get  error

### ISSUE THREAD

**Issue by 85636682** [PhamBaTho/BTNavigationDropdownMenu#19]
let menuView = BTNavigationDropdownMenu(title: items.first!, items: items) get  error
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by sameid** [comment]
I'm getting the same issue.

**Comment by nimblemindsapps** [comment]
same issue here

**Comment by avidalm9** [comment]
me too

**Comment by nimblemindsapps** [comment]
It fixed for me when I imported the whole source folder into xcode instead of just the swift file.

**Comment by jefferyleo** [comment]
Same issue! I wish the owner can fix it as soon as possible.

**Comment by javalnanda** [comment]
same issue !!

**Comment by bull-xu-stride** [comment]
For my project, the navigationController in line 190 causes this error, because I'm using a RESideMenu as the rootViewController of UIApplication.sharedApplication().keyWindow.

**Comment by bull-xu-stride** [comment]
The public init(title: String, items: [AnyObject]) constructor should also can specify a navigationController as a parameter to avoid this problem.

**Comment by 128keaton** [comment]
same issue here

**Comment by PhamBaTho** [comment]
I added navigationController as a param when initiating BTNavigationDropdownMenu instance. Please  check [latest release 0.3](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.3) in CocoaPods 
```public init(navigationController: UINavigationController? = nil, title: String, items: [AnyObject]) ```
Hope this issue can be solved. Feel free to reopen if anyone still experiences this issue.

**Comment by applecrusher** [comment]
I am getting an error for line 218 in BTNavigationDropDownMenu:
`let frame = CGRectMake(0, 0, titleSize.width + (self.configuration.arrowPadding + self.configuration.arrowImage.size.width)*2, self.navigationController!.navigationBar.frame.height)
`
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

I am not sure the issue. I am running Xcode 9 though. Anything advice may be obvious please give because I am new to swift.

**Comment by PhamBaTho** [comment]
@applecrusher the navigationController might be nill for some reasons. Check again navigationController or you can try [new release](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4) of this library to see if it could resolve your issue.
