### ISSUE TITLE
How can I customize this library to dropdown the menu from a floating navigation item, or from a navigationItem inside a container?

### ISSUE THREAD

**Issue by Glenncito** [PhamBaTho/BTNavigationDropdownMenu#20]

**Comment by Glenncito** [comment]
Regardless of where I place the navigationItem in the controller, the menu drops down from the NavBar at the top. If I remove the navbar, I get nil optional unwrapping error around this line: 
```let frame = CGRectMake(0, 0, titleSize.width + (self.configuration.arrowPadding + self.configuration.arrowImage.size.width)*2, self.navigationController!.navigationBar.frame.height)```

and If I create a container with a UIViewController inside that is imbedded in a UINavigationController, the dropdown still only occurs from the NavigationBar in the parent ViewController.

**Comment by PhamBaTho** [comment]
Hi @Glenncito, could you please use [new release 0.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.2). This release allows you to pass navigationController when initializing BTNavigationDropdownMenu. In your case, you can pass the most outside UINavigationController to make sure that the dropdown can show from the place you want to. 

Hope it helps!
