### ISSUE TITLE
Initial index

### ISSUE THREAD

**Issue by ErelOzcakirlar** [PhamBaTho/BTNavigationDropdownMenu#25]
How to set initial index ?

**Comment by bull-xu-stride** [comment]
1) Modify the BTTableView's selectedIndexPath not private. (Line 422)
2) In the Init constructor of BTNavigationDropdownMenu, add this line: self.tableView.selectedIndexPath = (items as? [String])?.indexOf(title)

**Comment by JimJty** [comment]
Arghh, this needs to be a fix.

**Comment by PhamBaTho** [comment]
I gave it a fix on  [latest release 0.3](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.3). From now on, you can set initial index like this `menuView = BTNavigationDropdownMenu(navigationController: self.navigationController, title: items[2], items: items)` where `title: items[2]` is the initial item.
