### ISSUE TITLE
Run Time Error on Xcode Version 7.1.1 (7B1005)

### ISSUE THREAD

**Issue by kpimichael** [PhamBaTho/BTNavigationDropdownMenu#30]
no errors during compile or in editor but when you go to a view that trys to instantiate the menu...you get a run time error as follows:
![2015-12-10_20-08-59 btnavigationdropdownmenu](https://cloud.githubusercontent.com/assets/537990/11733355/82a36d8e-9f7a-11e5-916f-b6417b07ec62.png)
![2015-12-10_20-08-59 btnavigationdropdownmenu2](https://cloud.githubusercontent.com/assets/537990/11733472/a7cedf02-9f7b-11e5-8a8b-a7a29fc6ba75.png)

Since i am totally new to Swift and Xcode, i do not know how to give any further information about errors such as logs.  If i can help tell me what to do.    

Thank you for sharing your code and expertise.

**Comment by PhamBaTho** [comment]
@kpimichael: I cannot reproduce this Run Time Error, please feel free to reopen this issue if it happens again. Thanks!
