### ISSUE TITLE
How to close programatically?

### ISSUE THREAD

**Issue by allaire** [PhamBaTho/BTNavigationDropdownMenu#31]
@PhamBaTho Is there a way to close the menu programatically? When I press my rightBarButtonItem with the menu opens, it remains open, I would like to close it in my Action.

Thanks!

**Comment by Spr-Luis** [comment]
@allaire 
Inside BTNavigationDropdownMenu.swift, I was added a word "public" before hideMenu method, and in your class you should make an instance of BTNavigationDropdownMenu and call hideMenu().
```swift
    
    public func hideMenu() {...}
```

In my case I made this:
```swift
override func viewWillDisappear(animated: Bool) {
        super.viewWillAppear(true)
        menuView.hideMenu()
    }
```

:)

**Comment by allaire** [comment]
@PhamBaTho Thoughts on making `hideMenu` public?

**Comment by PhamBaTho** [comment]
@allaire @Spr-Luis: I made showMenu() and hideMenu() functions public in [this release (0.2.1)](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.2.1). From now on, you can access to hide menu manually by using `menuView.hide()`. Thanks!

**Comment by allaire** [comment]
@PhamBaTho Thanks so much, keep up the good work!
