### ISSUE TITLE
Version 1.9, still crashes on init

### ISSUE THREAD

**Issue by stevesarkisian-tribpub** [PhamBaTho/BTNavigationDropdownMenu#32]
Looks like the fix for the old issue where the line "self.navigationController = UIApplication.sharedApplication().keyWindow?.rootViewController?.topMostViewController?.navigationController" was nil on init, was fixed by letting programmer pass in their own navigationController.

However, I'm noticing that the line "let window = UIApplication.sharedApplication().keyWindow!" crashes as well.  In my app, there is nothing set to keyWindow.

**Comment by 14T** [comment]
To make sure app is not crashing use #72

**Comment by PhamBaTho** [comment]
From [version 0.4](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4), I handled the case that navigationController and keyWindows could be nil like this:
```
guard let window = UIApplication.sharedApplication().keyWindow else {
   super.init(frame: CGRectZero)
   return
}

if let navigationController = navigationController {
   self.navigationController = navigationController
} else {
   self.navigationController = UIApplication.sharedApplication().keyWindow?.rootViewController?.topMostViewController?.navigationController
}
```
I believe that in this way, we can avoid potential crash bug. If you have any better solutions for any other concerns, please feel free to re-open this PR. Thanks!
