### ISSUE TITLE
有一个算bug，又不算bug的问题。

### ISSUE THREAD

**Issue by gf589462** [PhamBaTho/BTNavigationDropdownMenu#36]
![1](https://cloud.githubusercontent.com/assets/10599883/12032673/ac735a04-ae55-11e5-805a-be0673784f88.gif)

**Comment by Mamong** [comment]
是的 这个问题我看代码的时候已经发觉，内存泄露我也看出来了，我会在我的OC版本中尝试修复旋转，返回，泄露等问题

**Comment by PhamBaTho** [comment]
This bug is related to issue #14
