### ISSUE TITLE
Rotate Problem and Scrolling

### ISSUE THREAD

**Issue by termarco** [PhamBaTho/BTNavigationDropdownMenu#37]
Hi,
i have found two issue for this fantastic DropDownMenu. 
1. If the menu is opened and i rotate the device (from portrait to landscape)  there are problems. If the menu is opened and i rotate the device (from landscape to portrait) the navigation bar disappears.

![simulator screen shot 29 dic 2015 20 29 38](https://cloud.githubusercontent.com/assets/6470208/12040636/1242cdb4-ae6b-11e5-8e55-e638e798cd45.png)
![simulator screen shot 29 dic 2015 20 29 57](https://cloud.githubusercontent.com/assets/6470208/12040637/12438326-ae6b-11e5-847a-7920d87dbcee.png)

2. If the list contains many elements the scroll doesn't work

Thanks in advance.

**Comment by PhamBaTho** [comment]
@termarco Please check this GIF, when menu is open, and I rotate the device, everything seems normal.
- `If the menu is opened and i rotate the device (from landscape to portrait) the navigation bar disappears`. This is normal behavior of iOS, please check with native Messages app.
- `If the list contains many elements the scroll doesn't work`. This is related to issue #51.
