### ISSUE TITLE
Separator color

### ISSUE THREAD

**Issue by allaire** [PhamBaTho/BTNavigationDropdownMenu#4]
Hi,

Why is my first separator light (compared to your gif)? Also, how do I change the separator color altogether?

![](https://dl.dropboxusercontent.com/s/u6da5n7x22egj5g/2015-07-23%20at%2016.53.png)

Thanks!

**Comment by PhamBaTho** [comment]
That's weird, Mathieu. You can drag the dropdown menu down and you will see something like this: http://bit.ly/1LzyGlR. The first "separator" is not the actual separator itself. By default of iOS, there's always a dark shadow under the navigation bar. It's not created by the library. I just tried to make the lower separators have same height and same color with this default dark shadow. 

I spend a bit of time looking at your particular problem. I dug around and found that the custom navigation could also cause the problem, like setShadowImage for navigation bar or something like that.  So help please check again your navigation bar configuration. We can clone my Demo project also to make sure everything alright with your setting. Let me know if you find out something and I'm willing to help. Thanks

**Comment by allaire** [comment]
@PhamBaTho Just found out! I used `UINavigationBar.appearance ().barStyle = UIBarStyle.Black` and it must change the separator color :)

Also, would be cool to  be able to configure the separator color of the cells.

thanks!

**Comment by PhamBaTho** [comment]
Yeah, nice to know your problem has been fixed. I just pushed a [new commit](https://github.com/PhamBaTho/BTNavigationDropdownMenu/commit/55ab3352c84162160ee461238f4ce933345bcb62) that allows to set separator color of dropdown menu based on barStyle. I will also update this change to CocoaPods soon. Thanks.

**Comment by sinanulkuatam** [comment]
You can try something like         

`menuView.cellSeparatorColor = UIColor.greenColor().colorWithAlphaComponent(0.5)
`
