### ISSUE TITLE
DropdownMenu leaks memory

### ISSUE THREAD

**Issue by Skyb0rg** [PhamBaTho/BTNavigationDropdownMenu#41]
Hi,

i create a function which will create the DropdownMenu.
Every time i run this function 2mb of ram will get lost.

if i open a view like in you example close it an reopen it 5-10mb of ram are lost.

hope you understand what i mean.

i think it has something to do with "closures and strong reference cycle",
but i didn´t find the error.

Thanks.

**Comment by kyro38** [comment]
An `[unowned self]` is required in the init 
```
 self.tableView.selectRowAtIndexPathHandler = { [unowned self] (indexPath: Int) -> () in
            self.didSelectItemAtIndexHandler!(indexPath: indexPath)
            self.layoutSubviews()
        }
```

**Comment by csurbier** [comment]
@kyro38 i still have the same issue that @Skyb0rg  even with this modification. Any update?

Thanks
Christophe

**Comment by Skyb0rg** [comment]
Created a custom menu on my own, sorry.

Von meinem iPhone gesendet

**Comment by csurbier** [comment]
@Skyb0rg don't worry, i think i'm gonna to do the same or try to correct this library

**Comment by andykog** [comment]
Seems, that #45 fixes this

**Comment by PhamBaTho** [comment]
PR #45 merged. Thanks @andykog for your pull request :)
