### ISSUE TITLE
How to check which menu item is selected?

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [PhamBaTho/BTNavigationDropdownMenu#47]
I would like to check which item is selected in the menu.

Something like....

`let p = self.navigationDropDown!.selectedIndex`

I'm aware I could change the library directly - but I'm using Pods so would much prefer this was built into the library native.  

Possible?

Cheers!

**Comment by PhamBaTho** [comment]
@ianbradbury-bizzibody: How about this solution: 
In the closure, `menuView.didSelectItemAtIndexHandler = {(indexPath: Int) -> () in }`, we pass index value to a variable of view controller, like `selectedIndex = indexPath`. Please feel free to reopen this if you still have any issues. Thanks!
