### ISSUE TITLE
leaky views - adds subview to window (in init!), never removes it

### ISSUE THREAD

**Issue by argh** [PhamBaTho/BTNavigationDropdownMenu#52]
If you have the menu on a secondary page that gets opened on nav, every time you visit it it adds a new child subview to window.

"menuWrapper" is private, so you can't get access to it to force cleanup.

**Comment by argh** [comment]
Also, I don't think its a good practice to be doing any sort of view hierarchy modification in a constructor.

As a short term hack, I did this:   
 var leakyMenuView: UIView?
...
       let window = UIApplication.sharedApplication().keyWindow!
        let wv = Set(window.subviews)
        self.menuView = BTNavigationDropdownMenu(navigationController: self.navigationController, title: items.first!, items: items)
        let added = Set(window.subviews).subtract(wv)
        leakyMenuView = added.first

and then in my viewWillDisappear...        
  leakyMenuView?.removeFromSuperview()

**Comment by PhamBaTho** [comment]
Thanks. I will take a look

**Comment by Jeffdesu** [comment]
How is solution shown below?

if let navController = self.navigationController {
            navController.viewControllers[navController.viewControllers.count-1].view.addSubview(self.menuWrapper)
        } else {
            window.addSubview(self.menuWrapper)
        }

**Comment by PhamBaTho** [comment]
Added an attempt to fix this issue in [this commit](https://github.com/PhamBaTho/BTNavigationDropdownMenu/commit/934293ecc4d3c317dd77677a7f2be05934940503). Feel free to reopen if there is any further issue.
