### ISSUE TITLE
Configure a menu with a lot of items it's imposible to select the last one

### ISSUE THREAD

**Issue by ggdiez** [PhamBaTho/BTNavigationDropdownMenu#57]
Hello, 

With an item array with 15 items it's not possible to select the last option. 

`  self.menuView = BTNavigationDropdownMenu(navigationController: self.navigationController, title: items.first!, items: items)`

It's a Bug or there are any way to fix that.

Thank you.

![img_0273](https://cloud.githubusercontent.com/assets/2051473/15366769/2909b4fc-1d26-11e6-8928-543d8533dd56.PNG)

**Comment by PhamBaTho** [comment]
@ggdiez I've just had a fix for this issue in [release 0.4](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4)
