### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Sadmansamee** [PhamBaTho/BTNavigationDropdownMenu#59]
"direct field offset for BTNavigationDropdownMenu.BTNavigationDropdownMenu.(configuration in _2FD11A7176F1278EC9F8CADD0C8AF5A3) : BTNavigationDropdownMenu.BTConfiguration"

Over and Over again facing this issue.Whenever trying to initialize this issue occures.

**Comment by PhamBaTho** [comment]
@Sadmansamee Have you resolved this issue yet?

**Comment by PhamBaTho** [comment]
@Sadmansamee: could you share the way you solve this issue, I believe it could help others facing the same issue.
