### ISSUE TITLE
How to center

### ISSUE THREAD

**Issue by allaire** [PhamBaTho/BTNavigationDropdownMenu#6]
Hi @PhamBaTho,

I noticed that the title is not always centered depending on the device (iPhone 5s vs iPhone 6).

Do you have any tip?

**Comment by allaire** [comment]
Currently I'm using the view frame size like this : `BTNavigationDropdownMenu(frame: CGRectMake(0, 0, view.frame.width - 120, 44), title: filterLabels.first!, items: filterLabels, containerView: view)`

**Comment by PhamBaTho** [comment]
@allaire Could you make screenshots to spot the difference when displaying on iPhone 5S and iPhone 6? I tried to run on iOS Simulator with relevant iPhone devices, but I cannot sense your issue. Thanks.

**Comment by allaire** [comment]
@PhamBaTho I think that's because of the `rightBarButtonItem` I have. Can you give a try to add one in the demo?

**Comment by allaire** [comment]
Here's a screenshot on an iPhone 5s with a right bar button

![](https://dl.dropboxusercontent.com/s/mjcjinnv3dn47tn/2015-07-31%20at%2009.44.png)

**Comment by allaire** [comment]
@PhamBaTho I think that's because there is not enough room on small device when there's is button to fit and center the 300px titleView. It would be better to rely on the frame width in the demo I think.

See http://stackoverflow.com/questions/9921026/center-custom-title-in-uinavigationbar

**Comment by PhamBaTho** [comment]
@allaire Yeah, you're right. And your stackoverflow link have spotted the right thing to do with this issue. I have just made the small change on the source code that helps to `minimize the width of titleView` in the first place (please see this commit: ff5dbe08d949f729886216bdae6615419d5175e3). You don't have to pass `frame` param when initializing menuView anymore. Thanks :+1:

**Comment by allaire** [comment]
Why the `* 2` ? Also we should be careful with long title I think ?

**Comment by PhamBaTho** [comment]
When you increase the width of frame, it will stretching both ends of menuButton. So I have to `*2` to make sure it cover arrowImage completely.

About the long title, do you have any idea for that?

**Comment by allaire** [comment]
@PhamBaTho My idea would be to simply max the width of the title, let me do some testing :)

**Comment by PhamBaTho** [comment]
@allaire how about your testing so far? `Max the width of the title` is to minimize the width of the title, right? Could you show your solution for this?

**Comment by allaire** [comment]
@PhamBaTho Yeah, with a very long title it overlaps the buttons. maybe we should try to detect if there's any button, and if so, max width the title (frame width minus the navigationbarbutton width).

Thoughts?

**Comment by AaoIi** [comment]
Any one is able to center it in the title as that reference : http://stackoverflow.com/questions/9921026/center-custom-title-in-uinavigationbar ? 

please provide a demo of how to center it, this is so not the best practice : BTNavigationDropdownMenu(frame: CGRectMake(0, 0, view.frame.width - 120, 44), title: filterLabels.first!, items: filterLabels, containerView: view)

**Comment by PhamBaTho** [comment]
@allaire your idea on maximize the width of the title is great :+1: . I will consider to improve my source code. Thanks.
@AaoIi you might be using the out-of-date source code. We haven't passed `frame` param when initializing anymore. Please fetch this remote for the latest.

**Comment by AaoIi** [comment]
@PhamBaTho i see , but try updating the demo for the latest update :)
