### ISSUE TITLE
Alternate scope initialization

### ISSUE THREAD

**Issue by sinanku** [PhamBaTho/BTNavigationDropdownMenu#62]
Something like...

```
let menuView = BTNavigationDropdownMenu()

let items = ["Foo", "Bar"]

override func viewDidLoad() {
     super.viewDidLoad()
     menuView = BTNavigationDropdownMenu(navigationController: self.navigationController, title: "Main Menu", items: items)
}
```

This would help with keeping the navigation title static, as the menuView could re-initialize in viewDidAppear()

**Comment by PhamBaTho** [comment]
@sinanku yes, good idea. I've just fixed this issue in [release 4](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4). Now you can initialize menuView like this: (where `title` parameter doesn't need to be one of the items array)
```
menuView = BTNavigationDropdownMenu(navigationController: self.navigationController, title: "Main Menu", items: items)
```
Please feel free to reopen if it's still an issue for you. Thanks!

**Comment by sinanku** [comment]
@PhamBaTho awesome, thanks so much!

**Comment by PhamBaTho** [comment]
@sinanku You're welcome 🙂
