### ISSUE TITLE
More than a page of menu item

### ISSUE THREAD

**Issue by GZaccaroni** [PhamBaTho/BTNavigationDropdownMenu#63]
When there is more than a page of menu item i can't tap on the lasts because they are "hidden"

**Comment by PhamBaTho** [comment]
@GZaccaroni This issue is the same as issue #57. There's a fix for this issue in [release 0.4](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4). 

Don't hesitate to reopen if it's still an issue for you. Thanks!
