### ISSUE TITLE
Adding new items after initialized?

### ISSUE THREAD

**Issue by mat0pad** [PhamBaTho/BTNavigationDropdownMenu#68]
Is there an easier way to add new items for the dropdown menu after it has been initialized? 
Right now I'm recreating it but I'm experiencing crashes when doing this?

**Comment by mat0pad** [comment]
I suggest adding ad fun for updating data set:
`    public func updateData(items: [AnyObject])
    {
        if(!items.isEmpty)
        {
        self.tableView.items = items
    
        self.tableView.reloadData()
        }
    }`

**Comment by PhamBaTho** [comment]
@mat0pad As you wished, from [release 0.4](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.4) you can use `updateItems(items: [AnyObject])` to update items for the dropdown menu after it has been initialized.
Please feel free to reopen this issue if you have any further issues.
