### ISSUE TITLE
Bug in UpdateItems

### ISSUE THREAD

**Issue by burakozturk16** [PhamBaTho/BTNavigationDropdownMenu#73]
When you call updateItems after initialise; 
for example items = [] in viewDidLoad and you make http request to get your items and fill items finally updateItems new filled items array. 

I solve problem change this line at line 261

`self?.setMenuTitle("\(items[indexPath])")` 
to
`self?.setMenuTitle("\(self!.tableView.items[indexPath])")`

**Comment by PhamBaTho** [comment]
@burakozturk16 I've just fixed. Thanks!
