### ISSUE TITLE
Small fix for Swift2.3 (1)

### ISSUE THREAD

**Issue by glancashire** [PhamBaTho/BTNavigationDropdownMenu#85]
First thanks for your work!

To allow for compilation in Swift 2.3. Please wrap the context into a if let

...
 override func drawRect(rect: CGRect) {
        super.drawRect(rect)
		if let context = UIGraphicsGetCurrentContext() {
...

**Comment by PhamBaTho** [comment]
@glancashire: I created [a new branch](https://github.com/PhamBaTho/BTNavigationDropdownMenu/tree/swift-2.3) that supporting Swift 2.3. From now, you can use:

```pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-2.3'
```
Thanks so much for your both issues #85 #86

**Comment by glancashire** [comment]
many thanks

Graham Lancashire
