### ISSUE TITLE
Small fix for Swift2.3 (2)

### ISSUE THREAD

**Issue by glancashire** [PhamBaTho/BTNavigationDropdownMenu#86]
First thanks for your work!

To allow for compilation in Swift 2.3. Please change the occurrences of
...
       return context.countForFetchRequest(request, error: nil)
...
to
...
		do {
			return try context.countForFetchRequest(request)
		} catch {
			return 0
		}
...

**Comment by PhamBaTho** [comment]
Resolved in #85
