### ISSUE TITLE
Swift 3 Migration

### ISSUE THREAD

**Issue by sunshineclt** [PhamBaTho/BTNavigationDropdownMenu#89]
Hope it can support Swift 3 :)

**Comment by tulioht** [comment]
I am also expecting a swift version 3

**Comment by PhamBaTho** [comment]
@sunshineclt @tulioht  I have already pushed the [new branch](https://github.com/PhamBaTho/BTNavigationDropdownMenu/tree/swift-3.0) for Swift 3.0 syntax.  From now, you can use:

```
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
```
