### ISSUE TITLE
Possible to toggle by uibutton?

### ISSUE THREAD

**Issue by kiwo12345** [PhamBaTho/BTNavigationDropdownMenu#9]
Awesome work!

But is it possible to toggle the dropdown by a uibutton outside of the navigation bar?

**Comment by Out1and3r** [comment]
Yes, it is possible but requires some changes in the code. An easy way to do it is to make **func menuButtonTapped** public and instantiate main view with zero frame.

**Comment by PhamBaTho** [comment]
@kiwo12345 It's possible to trigger the dropdown menu by a button outside navigation bar. And @Out1and3r were right about reuse menuButtonTapped function. From my standpoint, there're still a lot of other factors that need to be considered when changing trigger from navigation bar to UIButton (e.g. changing dropdown menu UI properly, consider the position of dropdown menu, ...).

Btw, I dig around and found some useful libraries for your issue: https://github.com/kolyvan/kxmenu and https://github.com/bestwnh/IGLDropDownMenu. Hope it would help.

Thanks
