### ISSUE TITLE
Swift 3 error

### ISSUE THREAD

**Issue by Maryom** [PhamBaTho/BTNavigationDropdownMenu#90]
Hi,

I migrated to Swift 3 and I got the following error in BTConfiguration.swift:
`Cannot invoke initializer for type 'CGFloat' with an argument list of type '(CGFloat!)'`

<img width="757" alt="screen shot 2016-09-14 at 2 40 46 pm" src="https://cloud.githubusercontent.com/assets/3218401/18512162/7132b34c-7a90-11e6-9b3c-f098f24d4f86.png">

I tried to solve it but all my tries didn't work.

Any help?

Thanks.

**Comment by Maryom** [comment]
I solved it by replace it with the following line:
`return self.configuration.cellHeight as NSNumber!`

It's ok?

**Comment by Maryom** [comment]
Also, there is another error in RotationButton.swift in line 23:

`.green()`

Should be:

`.green`

I will add it in the PR as well.

**Comment by PhamBaTho** [comment]
I fixed this issue in [Swift-3.0 branch](https://github.com/PhamBaTho/BTNavigationDropdownMenu/tree/swift-3.0). Thanks!
