### ISSUE TITLE
Ability to programmatically select new index

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [PhamBaTho/BTNavigationDropdownMenu#92]
I need a button inside my table view to trigger a new index be selected in the dropdown menu, therefore updating the text in the nav bar to match the newly selected index.

**Comment by hslightnin** [comment]
+1, it would be nice to select a index on init also

**Comment by Vortec4800** [comment]
I think this is important as well.

**Comment by PhamBaTho** [comment]
The function `setSelected(index: Int)` is public now. It will be included in next release. Thanks.
