### ISSUE TITLE
Bunch of error in XCode 8

### ISSUE THREAD

**Issue by hebbian** [PhamBaTho/BTNavigationDropdownMenu#96]
Hi, I just installed XCode 8 today. This lib causes bunch of red error in the project, can you guys review it?

line 223 : `public var didSelectItemAtIndexHandler: ((indexPath: Int) -> ())?` 
line 562: `if let hitView = super.hitTest(point, withEvent: event) where hitView.isKindOfClass(BTTableCellContentView.self) {`

**Comment by Mohammed-Eliass** [comment]
Any ideas how to solve this ?

**Comment by PhamBaTho** [comment]
@hebbian @Mohammed-Eliass I have just added [support for Xcode 10 and Swift 4.2](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.5).
